# Generated by Django 2.2.7 on 2019-11-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gifts',
            field=models.ManyToManyField(blank=True, to='lists.Gift'),
        ),
    ]
