# Generated by Django 2.2.7 on 2019-11-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_profile_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
