# Generated by Django 2.2.7 on 2019-11-30 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0003_family_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='family_head',
            field=models.BooleanField(default=False),
        ),
    ]
