# Generated by Django 2.2.7 on 2019-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20191130_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_gifts',
            field=models.ManyToManyField(blank=True, to='lists.Gift'),
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_gifts',
            field=models.ManyToManyField(blank=True, related_name='assigned_gifts', to='lists.Gift'),
        ),
    ]
