# Generated by Django 2.2.7 on 2019-12-02 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0005_auto_20191201_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='giver',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gift_giver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='reciever',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gift_reciever', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
