# Generated by Django 2.2.7 on 2019-12-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0007_auto_20191202_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='reciever',
        ),
        migrations.AddField(
            model_name='gift',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
