# Generated by Django 2.2.7 on 2019-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20191202_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='reveal_names',
            field=models.BooleanField(default=False),
        ),
    ]
