# Generated by Django 2.2.7 on 2019-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_family_reveal_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_gifts',
        ),
        migrations.AddField(
            model_name='family',
            name='gifts_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
