# Generated by Django 2.2.7 on 2019-12-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20191206_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_gifts',
            field=models.ManyToManyField(blank=True, to='lists.Gift'),
        ),
    ]
